language: go

go:
  - 1.5

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover
  - go get -t .

script:
  - gotestcover -coverprofile="cover.out" -covermode="count" .

after_success:
  - goveralls -coverprofile="cover.out"